name: 'rawezh'
description : 'Say Hello'
author : 'Rawezh'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node14'
  main: 'dist/index.js'   